server:
  port: 9090
  servlet:
    context-path: /fyp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fyp?useSSL=false&allowPublicKeyRetrieval=true&maxReconnects=3&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos&jdbcCompliantTruncation=false
    username: root
    password: mayonnaise